# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce74ed9c7ec9c8403dc6f60a96a652fd13c8811e2783be36048217f7654c1ac9e99c41dac45e89ad79b2f797d6656d78eb6ce01a7e6501259173ad162308d30a

test:
  secret_key_base: 40ac8fcbd711b8650802b4bf7f46319cc05edc4957443019a8676fcc8a8990ea42f746b96f2fe925e8aa35b4c6504e6f10f25bcd415f3ebafe23382317861f85

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
